# GA Tracking ID
[googleAnalytics]
  ID = ""

[instagram]
  disableInlineCSS = true

[x]
  disableInlineCSS = true

# comments
[disqus]
# https://gohugo.io/templates/internal/#disqus
# disqusShortname = "your-disqus-shortname"
  shortname = ''
