# 用于构建和部署Hugo网站到GitHub Pages的示例工作流程
name: 分支【feature_gh-pages】自行创建 gh-pages分支，部署发布Hugo网站到Github Pages

on:
  # 在目标为默认分支的推送上运行
  push:
    branches:
      - feature_gh-pages
  # 允许您手动从“Actions”标签运行此工作流程（比如：可以在 GitHub项目的 Actions 中手动运行 workflow）
  workflow_dispatch:

jobs:
  build-deploy:   # 构建并部署
    runs-on: ubuntu-latest
    permissions:  # 新增权限配置
      contents: write  # 允许推送代码
      pages: write     # 允许部署 Pages
      id-token: write  # 允许 OIDC 令牌（如需）
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive  # 如果不需要子模块，可以删除
          fetch-depth: 0

      - name: 安装 Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo_version: 'latest'
          extended: true

      - name: 构建
        run: hugo --minify --gc

      - name: 部署
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public